### ISSUE TITLE
Re-enable tests related to max initcode size

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/edr#103]
This requires support for EIP-3860 in `revm::CfgEnv`, similar to [`limit_contract_code_size`](https://github.com/bluealloy/revm/blob/main/crates/primitives/src/env.rs#L92).

**Definition of Done**
Max initcode size tests are running successfully

Originally disabled in this commit: https://github.com/NomicFoundation/hardhat/pull/3916/commits/d4f6c0a2aae7164681f0a5a68970b45dcdfc6379

**Comment by agostbiro** [comment]
Hi, I'm trying to scope this issue. 

As I understand [`rethnet_evm_napi::ConfigOptions`](https://github.com/NomicFoundation/hardhat/blob/9ee04741dcf32baa9dcf62f5436b12a4a95e7da7/crates/rethnet_evm_napi/src/config.rs#L127) should get a `max_init_code_size` parameter which should then be passed on to REVM. Is this correct?

REVM doesn't support setting `max_init_code_size` in `revm::CfgEnv`, instead it [sets](https://github.com/bluealloy/revm/blob/9276c056a31e9be21add2d9907072d1ce130e5aa/crates/primitives/src/env.rs#L299) it to the double of the `revm::CfgEnv::limit_contract_code_size`.

So we have two ways implementing this change:

1. The quick hacky solution is that if `rethnet_evm_napi::ConfigOptions::max_init_code_size` is set, then set `revm::CfgEnv::limit_contract_code_size` to `max(ConfigOptions::max_init_code_size / 2, ConfigOptions::limit_contract_code_size)`
2. The cleaner solution is to submit a PR in REVM to support the `revm::CfgEnv::max_init_code_size` parameter. This path will be obviously slower.

Which one should we do?

**Comment by Wodann** [comment]
The idea of this task is to add the feature to `revm`

**Comment by Wodann** [comment]
When making changes to `revm`, make sure to branch from this branch: https://github.com/Wodann/revm/tree/refactor/decouple-inspector-evm-data

**Comment by agostbiro** [comment]
Closed in https://github.com/NomicFoundation/hardhat/pull/4448
