### ISSUE TITLE
Get benchmarks running in a reasonable amount of time

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#106]
**Definition of Done**
Individual benchmarks should run for a maximum (in most cases) of the Criterion "benchmark times". If I recall correctly, it is 3-5 seconds.

**Comment by feuGeneA** [comment]
From Slack yesterday:

> Remco Kuijper
>   [5:48 PM](https://nomicfoundation.slack.com/archives/D03UM864C8J/p1689284884339849)
> One thing that we might be able to do is to decouple the parametrisations. Currently it grows exponentially with each parametrisation, but if we for example only:
> - vary the number of checkpoints for the maximum number of accounts
> - vary the number of snapshots for the maximum number of accounts
> 
> this might reduce the load a little

**Comment by Wodann** [comment]
Before making any such changes, make sure to run (some of) the benchmarks with `tracing` to see what's taking so long

**Comment by Wodann** [comment]
This is outdated
