### ISSUE TITLE
Investigate impact of changing `web3_clientVersion` response

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#138]
Previously we reported a web3_clientVersion string containing: Hardhat & ethereumJS version. Now we're returning EDR and revm versions. What will the impact of this change be on Hardhat users? Is anyone actively using this API?

**Definition of Done**
- An analysis of impact on the Hardhat ecosystem
- Potential mitigation strategy

**Comment by agostbiro** [comment]
We discussed this with @fvictorio and settled on monkey patching the value returned by EDR in Hardhat to create version strings like: `HardhatNetwork/2.19.0/@nomicfoundation/edr/0.2.0-dev`

https://github.com/NomicFoundation/hardhat/blob/8ddd066e902cac3e3689a2db50e557e76fad993b/packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts#L516
