### ISSUE TITLE
Split JSON-RPC logic from Node logic

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#141]
We want to split the JSON-RPC layer from the code logic, allowing us to:
- reuse the Eth business logic in the Node without the JSON-RPC server logic
- create custom error conversions between inner types and RPC errors

An example of this separation was created in https://github.com/NomicFoundation/hardhat/pull/4363

**Definition of Done**
- Port all existing JSON-RPC method implementations in `rethnet_rpc_server` to `node.rs`
- Split each ported method into a separate PR (as far as possible) to simplify review and minimise merge conflicts
- Unit/Integration test the individual `Node` APIs in Rust

**Comment by feuGeneA** [comment]
backlink: [crates/rethnet_rpc_server/src/lib.rs](https://github.com/NomicFoundation/hardhat/pull/4132/files/2f6265e4df65cb393fb1f41bbc858c9f2dc0c09f#diff-7fb90f8440012547242c5a3f6302ffe2c0e2e1803d94d148db39dfd46f64be6d)
(that's a link to a resolved discussion in [crates/rethnet_rpc_server/src/lib.rs` on (post-changes) line 291, but at the time of this writing, github can't link to resolved discussions.)

**Comment by feuGeneA** [comment]
What do you think about the idea of introducing TWO new traits here, one of those being the one you suggested, eg `EthRequestHandler` whose interfaces deal only with types native to the underlying EDR code, but also an additional trait, something like `JsonRpcRequestHandler`, that translates those EDR-native types into the types expected by the JSON-RPC interface.

You had represented that latter translation with your `to_rpc_response_data` function, but I don't think a single function can serve all cases, as there are nuances between one method and another, even when those different methods accept or return the same data types.

For example, `eth_blockNumber` should return a `U256` _without_ leading zeroes, but `eth_getStorageAt` should return a `U256` _with_ leading zeroes. As another example, `evm_increaseTime` accepts a `U256`, but that value can come as either a hex-encoded string or a _decimal_-encoded string. And as a final example, `evm_increaseTime` should return a `U256`, but it should be in the form of a _decimal_-encoded string.

I suspect that capturing these nuances between the different methods would be a good use case for an additional trait. And then the `axum` `Router` would be a layer above _that_. What do you think?

**Comment by Wodann** [comment]
For reference, a past proposal for also splitting validation and JSON-RPC logic exists here:
https://github.com/NomicFoundation/hardhat/commit/432068aa304ca2d5b7049c933f64914bbddaef0f
