### ISSUE TITLE
Port `hardhat_*` config JSON-RPC APIs (part 2)

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#145]
**Definition of Done**
Port the following configuration-related APIs:
- [x] hardhat_metadata ([source](https://github.com/NomicFoundation/hardhat/blob/7dd2586cf5be393492f70adb176ab85a6e79b792/packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts#L285))
- [x] hardhat_setCoinbase ([source](https://github.com/NomicFoundation/hardhat/blob/7dd2586cf5be393492f70adb176ab85a6e79b792/packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts#L381))
- [x] hardhat_setNextBlockBaseFeePerGas ([source](https://github.com/NomicFoundation/hardhat/blob/7dd2586cf5be393492f70adb176ab85a6e79b792/packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts#L364))
- [x] hardhat_setPrevRandao ([source](https://github.com/NomicFoundation/hardhat/blob/7dd2586cf5be393492f70adb176ab85a6e79b792/packages/hardhat-core/src/internal/hardhat-network/provider/modules/hardhat.ts#L416))

Avoid type conversions within EDR, e.g. reuse `CfgEnv` such that it can be passed into `revm` if possible

Continuation of https://github.com/NomicFoundation/rethnet/issues/116

**Comment by agostbiro** [comment]
Make sure to fix the TODO in `mine_block` of the RPC server.
