### ISSUE TITLE
`hardhat_mine` is slow

### ISSUE THREAD

**Issue by feuGeneA** [NomicFoundation/edr#157]
Hardhat had implemented `hardhat_mine` with a "reserved blocks" scheme, avoiding the mining of empty blocks and simply leaving them unallocated unless/until they're actually accessed.

For EDR, our initial implementation of `hardhat_mine` was a naive one, simply calling `mine_block()` in a loop for the requested number of blocks, with an intention to optimize later of necessary. At this point, that optimization does already seem necessary.

Some of the provider tests in the Hardhat codebase ask `hardhat_mine` to mine a _lot_ of blocks, including one test that asks for a _billion_. Many of those tests are simply failing with network timeouts:
![image](https://github.com/NomicFoundation/rethnet/assets/7883777/4ba32247-691a-4f12-9d50-421addbef8d5)

For a quantitative comparison, here is some "benchmark" data as output by the mocha test runner:
![image](https://github.com/NomicFoundation/rethnet/assets/7883777/9ab304ee-613f-4744-ad7f-c6a8b4c492ac)

![image](https://github.com/NomicFoundation/rethnet/assets/7883777/4a0d40b7-33d1-470a-94f7-225ac0347d4a)

![image](https://github.com/NomicFoundation/rethnet/assets/7883777/a32912d7-ca49-4721-8018-a3ea70774091)

**Comment by Wodann** [comment]
Resolved by https://github.com/NomicFoundation/hardhat/pull/4341
