### ISSUE TITLE
Research zeroizing secret keys

### ISSUE THREAD

**Issue by agostbiro** [NomicFoundation/edr#162]
We should ideally zeroize secret keys in EDR for good cryptographic hygiene. This is not trivial to for two reasons:

1. Secret keys might be passed from/to Node via FFI.
2. We should store the keys boxed so that when a key gets moved, no copies are made of the key material. This would be a problem, because we couldn't zeroize those copies ([more info](https://benma.github.io/2020/10/16/rust-zeroize-move.html)).

More research should be done to understand what we can do.

**Definition of done**

A document detailing feasibility and possible approaches.

**Comment by fvictorio** [comment]
We decided that this is out of scope for now.
