### ISSUE TITLE
Call `update` inside `set_block_gas_limit`

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#188]
Currently, we're calling the `MemPool::update` function external to the mem pool when changes to it have occurred. For correctness, this should happen internal to the `MemPool` whenever a change occurs that would change the validity of pending/future transactions.

**Definition of Done**
- Call `update` inside the `set_block_gas_limit` function (in EDR and Hardhat)
- Remove calls to `update` after `set_block_gas_limit` (in EDR and Hardhat)
- Validate whether any other `MemPool` APIs would benefit from this general approach

**Comment by agostbiro** [comment]
Would removing calls to `update` after `set_block_gas_limit` need changes in EthereumJS VM as well? I noticed that it's the [node](https://github.com/NomicFoundation/hardhat/blob/aa7a04f740d0be41ab491dc08bdde563be52bb42/packages/hardhat-core/src/internal/hardhat-network/provider/node.ts#L1164C21-L1164C21) making this calls, not the vm adapters.

**Comment by Wodann** [comment]
Yes, it would require the same change to happen in the ethereumjs adapter
