### ISSUE TITLE
`edr_evm_napi::PendingTransaction.create` deadlocks

### ISSUE THREAD

**Issue by agostbiro** [NomicFoundation/edr#189]
When calling many instances of `edr_evm_napi::PendingTransaction.create` in parallel from JS and awaiting them with `Promise.all`, the promise never resolves. Relevant code:

https://github.com/NomicFoundation/hardhat/pull/4398/files#diff-b3387221260f0e775eeb57f850b55eb260257487157b11c9ba92bc88eef84a9eR390

**Definition of done**

Switch to `Promise.all` from sequential in the linked code and make sure debug trace call JS tests pass in `edr` mode.

**Comment by Wodann** [comment]
The component-based implementations have been removed from `edr_napi`, so no need to fix this anymore
