### ISSUE TITLE
Validate that Hardhat doesn't have performance regressions in ethereumjs mode

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#195]
We need to validate that the ethereumjs performance is similar to the performance of the currently used version of Hardhat in third-party projects.

**Definition of Done**
- [x] Test in [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts) (Agost WIP on benchmark server)
- [x] Test in https://github.com/NexusMutual/smart-contracts (Agost WIP on benchmark server)
- [x] Test in https://github.com/ProjectOpenSea/seaport/ (Agost WIP on benchmark server)
- [x] Decide whether to test more based on https://www.notion.so/nomicfoundation/Testing-with-real-projects-bd896ef0b11c45fbb41eeb6df16e6584

**Comment by agostbiro** [comment]
Test command: `npx hardhat test`. The reported time is a median of 3 runs.

## [Uniswap/v3-core](https://github.com/Uniswap/v3-core) @ `d8b1c63` ✅ 

hardhat 2.2.0 (from lockfile)
71 seconds

hardhat 2.18.1
84 seconds ⚠️

hardhat [b2a551f73](https://github.com/nomicFoundation/hardhat/commits/b2a551f73) (main)
85 seconds ⚠️

hardhat [a08c12d](https://github.com/nomicFoundation/hardhat/commits/a08c12d) (rethnet/main)
85 seconds ✅ 

## [openzeppelin-contracts](https://github.com/OpenZeppelin/openzeppelin-contracts) @ `6383299d` ✅ 

hardhat 2.17.3 (from lockfile)
885 seconds

hardhat [a08c12d](https://github.com/nomicFoundation/hardhat/commits/a08c12d) (rethnet/main)
676 seconds ✅ 

## [NexusMutual/smart-contracts](https://github.com/NexusMutual/smart-contracts) @ `7ff5f3a4` ❌

[Test failure](https://github.com/NomicFoundation/edr/issues/183#issuecomment-1772933366)

## [seaport](https://github.com/ProjectOpenSea/seaport/) @ `6d8bf57d` ❌

[Test failure](https://github.com/NomicFoundation/edr/issues/183#issuecomment-1772933366)

## [synthetix](https://github.com/Synthetixio/synthetix) @ `3040126f` ❌

[Test failure](https://github.com/NomicFoundation/edr/issues/183#issuecomment-1772933366)

**Comment by Wodann** [comment]
@agostbiro Is the OpenZeppelin benchmark run with EDR mode or Ethereumjs mode?

**Comment by agostbiro** [comment]
> @agostbiro Is the OpenZeppelin benchmark run with EDR mode or Ethereumjs mode?

Should be with EthereumJS mode.
