### ISSUE TITLE
Release `solidity-coverage`

### ISSUE THREAD

**Issue by agostbiro** [NomicFoundation/edr#202]
Releasing this [change](https://github.com/sc-forks/solidity-coverage/pull/817) in [solidity-coverage](https://github.com/sc-forks/solidity-coverage) is a blocker for releasing Hardhat with EthereumJS mode by default.

**Definition of done**

Release a new version of [solidity-coverage](https://github.com/sc-forks/solidity-coverage) on NPM with this [change](https://github.com/sc-forks/solidity-coverage/pull/817).

**Comment by Wodann** [comment]
We decided to add a facade in Hardhat to avoid needing this change/release in `solidity-coverage`: https://github.com/NomicFoundation/hardhat/pull/4481
