### ISSUE TITLE
Test the missing cases in blokchain- and transaction-related getters of the Node

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/edr#219]
In https://github.com/NomicFoundation/hardhat/pull/4535 I implemented a set of getters to the `Node`. I left some of those tests incomplete, as to generate those scenarios I'd prefer to have mining-related API's already available in the `Node`.

**Definition of Done**
Add tests for the following functions:
- [ ] `block_transaction_count_by_hash`
- [ ] `block_transaction_count_by_block_spec`
- [ ] `transaction_by_block_hash_and_index`
- [ ] `transaction_by_block_spec_and_index`
- [ ] `transaction_count`
- [ ] `transaction_by_hash`
- [ ] `transaction_receipt`

**Comment by fvictorio** [comment]
No longer relevant?
