### ISSUE TITLE
Expose `edr_provider::handle_request` method in N-api

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#231]
**Definition of Done**
- Add a `Provider` class to N-API, with a constructor for a `ProviderConfig`
- Add a `pub fn Provider::handle_request(request: &str) -> String` to the N-API crate, that deserializes the JSON request and forwards it to `edr_provider::handle_request`

**Comment by fvictorio** [comment]
I think we can close this one, right?
