### ISSUE TITLE
EDR provider should accept request without params

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/edr#234]
The EDR provider fails if the JSON-RPC request doesn't have a `params` field. But this field is optional in EIP-1193, so I think it should be optional in the EDR provider too.

This is not super important because we can handle it in the Hardhat side if necessary, but I think we should do it eventually.

**Comment by Wodann** [comment]
Based on the discussion we had externally to GitHub, it sounds like we'll not focus on making EDR's provider EIP-1193 compliant, but rather leave it up to Hardhat to make an EIP-1193 version of a provider.
