### ISSUE TITLE
Internally handle failed batch requests due to type changes

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#239]
When the cached type doesn't match the expected type for a batch request item, we currently delete the cache item and fail the call. Instead, we should delete the cache item and then proceed to fetch the request from the remote.

There are two ways to go about this:

1. Have the generic batch request method return concrete types instead of `serde_json::Value`. This would be the preferable solution, but heterogenous lists are difficult to express with the Rust type system.
2. Handle it in methods that use the generic batch request method to make concrete batch calls.

Related #238 

**Definition of done**

When the cached type doesn't match the expected type for a batch request item, the faulty cache item is deleted and the request is fetched the request from the remote.

**Comment by fvictorio** [comment]
No longer relevant.
