### ISSUE TITLE
Collect `console.log` messages

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#241]
Hardhat collects all calls to `console.log` in Solidity using [this code](https://github.com/NomicFoundation/hardhat/blob/edr/main/packages/hardhat-core/src/internal/hardhat-network/stack-traces/consoleLogger.ts).

Hardhat Network implements `console.log` by tracing everything. In EDR, we will use a precompiled contract instead.

This should be supported for all "calls" and "mining operations":
- `eth_call`
- `evm_mine`
- `eth_send[Raw]Transaction`
- `hardhat_mine`
- interval mining

`console.log` is always enabled, so the callback for handling `console.log` messages should be passed into the constructor of the N-API `struct Provider`. The callback should return ABI-encoded data as a `Buffer`.

In the future, we might investigate formatting the output as a string and returning that instead. For this issue, that is out of scope.

**Definition of Done**
- Implement a means of collecting all `console.log` calls upon running a Solidity smart contract
- Call a JS callback after a transaction is mined with the collected `console.log` messages
- Implement a test runner for [these JSON files](https://github.com/NomicFoundation/hardhat/tree/edr/main/packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files). Also, see [README](https://github.com/NomicFoundation/hardhat/blob/edr/main/packages/hardhat-core/test/internal/hardhat-network/stack-traces/README.md)

**Comment by alcuadrado** [comment]
I don't think so

**Comment by agostbiro** [comment]
Done in https://github.com/NomicFoundation/hardhat/pull/4659 except for "Implement a test runner for [these JSON files](https://github.com/NomicFoundation/hardhat/tree/edr/main/packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files)." Should I make a new task for this?

**Comment by Wodann** [comment]
That works! 👍

**Comment by agostbiro** [comment]
Closing with follow up https://github.com/NomicFoundation/edr/issues/245
