### ISSUE TITLE
Define strategy for handling stack trace generation and error handling of Solidity

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#242]
We should revisit the Hardhat stack trace generation [code](https://github.com/NomicFoundation/hardhat/tree/edr/main/packages/hardhat-core/src/internal/hardhat-network/stack-traces) and come up with a better approach to do it in EDR.

**Definition of Done**
- Define a strategy for handling stack trace generation in EDR
- Define a strategy for Solidity error handling in EDR

**Comment by Wodann** [comment]
https://www.notion.so/nomicfoundation/Stack-traces-generation-and-error-inference-porting-strategy-04d9c48cbea0447086e2447cdc5db85e

**Comment by alcuadrado** [comment]
Done. See #246
