### ISSUE TITLE
Implement a test runner for Hardhat stack traces & console log messages

### ISSUE THREAD

**Issue by agostbiro** [NomicFoundation/edr#245]
Follow up from https://github.com/NomicFoundation/edr/issues/241

Implement a test runner for Hardhat stack trace console log messages.

**Definition of Done**

Implement a test runner for [these JSON files](https://github.com/NomicFoundation/hardhat/tree/edr/main/packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files). Also, see [README](https://github.com/NomicFoundation/hardhat/blob/edr/main/packages/hardhat-core/test/internal/hardhat-network/stack-traces/README.md)

**Comment by fvictorio** [comment]
See https://github.com/NomicFoundation/edr/issues/266#issuecomment-2100963981
