### ISSUE TITLE
Re-enable end-to-end tests

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#249]
We moved Hardhat's end-to-end tests to the [test-edr-failing folder](https://github.com/NomicFoundation/hardhat/tree/edr/main/packages/hardhat-core/test-edr-failing) to ensure that CI would continue working once we added EDR as a provider.

Now that `eth_sendTransaction` and `eth_call` have been implemented we can start re-enabling theses tests.

Tests that should succeed, but are failing in `packages/hardhat-core/test/internal/hardhat-network/provider`:

- [x] ../console-log.ts (Agost WIP)
- [x] hardhat-network-options.ts (Agost WIP)
- [x] forking-different-hardfork.ts (Agost WIP)
- [x] selfdestruct.ts (Agost WIP)
- [x] modules/eth/methods/index.ts (Agost WIP)
- [x] modules/eth/hardforks.ts (Agost WIP)
- [x] modules/eth/methods/sendRawTransaction.ts (Agost WIP)
- [x] modules/hardhat.ts (Remco WIP)
- [x] forked-provider.ts (Remco)
- [x] node.ts
- [x] baseFeePerGas.ts (Agost WIP)
- [x] modules/eth/blockTags.ts
- [x] modules/eth/chainId.ts
- [x] modules/personal.ts
- [x] modules/eth/methods/getCode.ts
- [x] modules/net.ts
- [x] modules/eth/methods/getStorageAt.ts
- [x] modules/web3.ts

**Definition of done**
- Move all test files in `test-edr-failing` back to the `test` folder in Hardhat Network and have them succeed

**Comment by agostbiro** [comment]
Can't link more PRs so I'll just comment them:

https://github.com/NomicFoundation/hardhat/pull/4705

https://github.com/NomicFoundation/hardhat/pull/4704

**Comment by agostbiro** [comment]
https://github.com/NomicFoundation/hardhat/pull/4723

https://github.com/NomicFoundation/hardhat/pull/4724

**Comment by agostbiro** [comment]
https://github.com/NomicFoundation/hardhat/pull/4746

**Comment by agostbiro** [comment]
https://github.com/NomicFoundation/hardhat/pull/4751

https://github.com/NomicFoundation/hardhat/pull/4751

**Comment by agostbiro** [comment]
https://github.com/NomicFoundation/hardhat/pull/4756

https://github.com/NomicFoundation/hardhat/pull/4753
