### ISSUE TITLE
Add support for EIP-2930 transactions in `eth_call` request resolution

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#255]
Currently, `eth_call` can only resolve requests to EIP-155 or EIP-1559 transactions to match Hardhat's behaviour. It should however also support EIP-2930 transactions.

**Definition of Done**
Add support for resolution of an `eth_call` request to an EIP-2930 transaction

**Comment by alcuadrado** [comment]
I believe those should only be used in two cases:

1. When you are running Berlin and an access list is provided.
2. When running >= London and an access list and `gasPrice` is provided.

**Comment by Wodann** [comment]
Resolved by https://github.com/NomicFoundation/hardhat/pull/4746
