### ISSUE TITLE
Re-enable stack trace tests

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#266]
**Depends on**
- [ ] #245 

**Definition of Done**
Port Hardhat stack trace [JSON files](https://github.com/NomicFoundation/hardhat/tree/edr/main/packages/hardhat-core/test/internal/hardhat-network/stack-traces/test-files) to the new EDR format, resulting in passing tests. Also, see [README](https://github.com/NomicFoundation/hardhat/blob/edr/main/packages/hardhat-core/test/internal/hardhat-network/stack-traces/README.md). 

**WIP**
_list the JSON files that you're currently working on or have already completed porting_

**Comment by fvictorio** [comment]
This is spread over the issues in https://github.com/NomicFoundation/edr/issues/246, as part of the way we are going to implement those (gradually migrating the relevant tests).
