### ISSUE TITLE
Replayed blocks failures

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/edr#306]
This issue collects the errors we find by replaying blocks on EDR. Before working on one, please convert it to an issue.

- [x] Blocks `19318016` and `19318018`. Error: `Sender doesn't have enough funds to send tx`

**Comment by Wodann** [comment]
Bugs when running blocks `19318016` and `19318018` are fixed by https://github.com/NomicFoundation/hardhat/pull/4940
