### ISSUE TITLE
EDR performance benchmark infra

### ISSUE THREAD

**Issue by agostbiro** [NomicFoundation/edr#313]
Tracking issue for EDR performance benchmark infra

- [x] https://github.com/NomicFoundation/hardhat/pull/4928
- [x] https://github.com/NomicFoundation/edr/issues/309
- [x] https://github.com/NomicFoundation/edr/issues/310
- [x] https://github.com/NomicFoundation/edr/issues/311
- [x] https://github.com/NomicFoundation/edr/issues/312
- [x] https://github.com/NomicFoundation/edr/issues/338
- [x] https://github.com/NomicFoundation/edr/issues/337

**Comment by Wodann** [comment]
@agostbiro is there any follow-up that needs to be added to this tracking issue?
