### ISSUE TITLE
Overriding a storage slot of a fork does not work anymore

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/edr#324]
See https://github.com/NomicFoundation/hardhat/issues/4970

Reproduction steps: run the following code while forking mainnet.

```js
  const DAI_ADDRESS = "0x6b175474e89094c44da98b954eedeac495271d0f";

  const totalSupplyBefore = await network.provider.send("eth_call", [{
    to: DAI_ADDRESS,
    data: "0x18160ddd"
  }])
  console.log(totalSupplyBefore)

  await network.provider.send("hardhat_setStorageAt", [DAI_ADDRESS, "0x1", "0x0000000000000000000000000000000000000000000000000000000000000000"])
  
  const totalSupplyAfter = await network.provider.send("eth_call", [{
    to: DAI_ADDRESS,
    data: "0x18160ddd"
  }])
  console.log(totalSupplyAfter)
```

In `hardhat@2.20.1`, this logs the expected:

```
0x00000000000000000000000000000000000000000a2ef5aaef273d3af690cd38
0x0000000000000000000000000000000000000000000000000000000000000000
```

but in `hardhat@2.21.0`, we get:

```
0x00000000000000000000000000000000000000000a2ef5aaef273d3af690cd38
0x
```

This causes problems when a library (like ethers) tries to decode the result.

**Comment by Wodann** [comment]
The above example merely shows a formatting difference: `0x` is zero. This seems correct according to the execution API spec: https://ethereum.github.io/execution-apis/api-documentation/

![image](https://github.com/NomicFoundation/edr/assets/6917585/aa5d4597-3920-4e0b-9072-07902cc75246)

**Comment by Wodann** [comment]
Could it be that `ethers` is expecting a padded result?

**Comment by Wodann** [comment]
I wasn't able to reproduce the failure in storage slot overriding. Both setting to zero and to a non-zero value works: https://github.com/NomicFoundation/hardhat/commit/7c51e0b0619352c59764f63848be971b85a3df40

**Comment by fvictorio** [comment]
Sorry @Wodann, these reproduction steps weren't very good.

If you set the storage slot to `0x0000000000000000000000000000000000000000000000000000000000000001`, you also get `0x` with HH+EDR, but HH+EJS returns the corect value.
