### ISSUE TITLE
Error when sending an estimate gas with almost the same parameters as a non-minable tx in the mempool

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/edr#326]
This is all I could narrow down the problem:

```js
  const [a] = await network.provider.send("eth_accounts", [])
  await network.provider.send("evm_setAutomine", [false])

  await network.provider.send("hardhat_setNextBlockBaseFeePerGas", ["0x100"])
  await network.provider.send("hardhat_mine", [])

  await network.provider.send("eth_sendTransaction", [{
    from: a, to: a, nonce: "0x0", maxFeePerGas: "0xA"
  }])

  await network.provider.send("eth_estimateGas", [{
    from: a, to: a, nonce: "0x0", maxFeePerGas: "0x200"
  }])
```

Explanation:
- We disable automining
- Then we set the base fee to some value
- After that we send a tx with a `maxFeePerGas` below the base fee. This means that this tx will be in the mempool but it won't be minable.
- Finally, we send an `eth_estimateGas` with the same nonce as the tx in the mempool, but with a minable `maxFeePerGas`.

This works fine in `hardhat@2.20.1` but it throws this in `hardhat@2.21.0`:

```
ProviderError: Invalid transaction: NonceTooHigh { tx: 1, state: 0 }
```

Interestingly, this error comes directly from REVM, not from EDR, which seems to suggest there's something wrong with our logioc.

**Comment by Wodann** [comment]
I ran the repro steps in both `ethereumjs/main` and `main`. We are doing the except same steps as you described, except that `ethereumjs/main` [disables the nonce check](https://github.com/NomicFoundation/hardhat/blob/ethereumjs/main/packages/hardhat-core/src/internal/hardhat-network/provider/node.ts#L2667).

We'll have to introduce that config option in `revm` to mimick `ethereumjs`.
