### ISSUE TITLE
Virus Alert By Kaspersky

### ISSUE THREAD

**Issue by FranciscoBSpadaro** [NomicFoundation/edr#330]
virus crypto mining = edr.win32-x64-msvc.node   " node_modules\@nomicfoundation\edr.win32-x64-msvc\
![imagem_2024-03-11_105649262](https://github.com/NomicFoundation/edr/assets/69543568/053b2db5-9763-459b-a0b5-48625df0d717)
 "
is this a virus or not ?

can i ignore it as fake alert?

**Comment by fvictorio** [comment]
It seems like a fake alert, yes.

If you have the rust toolchain installed, you can clone [the Hardhat repo](https://github.com/nomiclabs/hardhat), run `pnpm install && pnpm build`, and verify that the checksum of the binary built under `crates/edr_napi` matches the one installed by npm.
