### ISSUE TITLE
Add a function that receives a hardfork and returns the list opcodes activated for that hardfork

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/edr#332]
**Definition of done**

A function can be imported from `@nomicfoundation/edr` and used to get the list of opcodes for a given hardfork. I think just having the opcodes names is enough. @zemse can you confirm that?

**Comment by zemse** [comment]
> I think just having the opcodes names is enough

Sorry for the delay in response. Yes, just the names of activated opcodes are enough.

**Comment by fvictorio** [comment]
@zemse confirmed that he can do this on his side.
