### ISSUE TITLE
Test deployment time of MUD framework

### ISSUE THREAD

**Issue by agostbiro** [NomicFoundation/edr#353]

**Comment by agostbiro** [comment]
5 sec median with `anvil 0.2.0 (9881e7d 2024-03-28T00:16:50.896678000Z)` and 5.7 sec median with Hardhat Node using `hardhat=2.22.2`.

**Comment by jwbda** [comment]
Hi, @agostbiro @Wodann , Is this `eth_maxPriorityFeePerGas - Method not supported` warning/error solve? In my machine it still exist. 

Reproduce proccdures is :
- On one terminal, run `npx hardhat node` command.
- On other terminal, run `npx hardhat test --network localhost`

And the result is :
> eth_blockNumber
> eth_chainId
> web3_clientVersion
> eth_getBlockByNumber
> eth_accounts
> hardhat_metadata (20)
> eth_accounts
> hardhat_metadata (20)
> eth_blockNumber
> eth_getBlockByNumber
> eth_feeHistory
> eth_maxPriorityFeePerGas - Method not supported (!!! here is the warning)
> eth_sendTransaction
>   Contract deployment: Lock
>   Contract address:    0x5fbdb2315678afecb367f032d93f642f64180aa3
>   Transaction:         0x49750550d8fde7036a17cadd1dd81c637ce4384980673a5bdfeaf39d4d70e0a8
>   From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
>   Value:               1. gwei
>   Gas used:            326112 of 30000000
>   Block #1:            0xb598d31260640bc3e7718e94f960daa623694d82677a34a38416c06685bb9959
> 
> eth_getTransactionByHash
> evm_snapshot
> eth_call
>   Contract call:       Lock#unlockTime
>   From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
>   To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3
> 
> evm_revert
> evm_snapshot
> eth_call
>   Contract call:       Lock#owner
>   From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
>   To:                  0x5fbdb2315678afecb367f032d93f642f64180aa3
> 
> evm_revert
> evm_snapshot
> eth_getBalance
> eth_getBlockByNumber
> eth_accounts
> hardhat_metadata (20)
> eth_blockNumber
> eth_feeHistory
> eth_sendTransaction

**Comment by jwbda** [comment]
BTW, What is the `MUD` stand for? @agostbiro, thanks in advance.

**Comment by fvictorio** [comment]
@jwbda that method is not implemented yet. There is a Hardhat issue about it (https://github.com/NomicFoundation/hardhat/issues/4365) and I just created a sibling EDR issue to track it here (https://github.com/NomicFoundation/edr/issues/369). But in general, it shouldn't be a big issue that it's not implemented. You see that message because the library you are using (ethers.js or whatever) is trying to use the method, but it will likely work anyway if it isn't there.

MUD is https://mud.dev/

**Comment by jwbda** [comment]
Thank you @fvictorio for reply. this reply is really fast as like spaceX rocket. I will follow the (https://github.com/NomicFoundation/edr/issues/369) issue to see what is the implementation.

And thanks again for this reply. Have a good day.
