### ISSUE TITLE
Can't fork a local node from avax public rpc

### ISSUE THREAD

**Issue by Ajezezzzz** [NomicFoundation/edr#362]
### Version of Hardhat

2.22.2

### What happened?

When I try to start a forked local node from the Avax network using the public RPC, I always receive the same error.
Error HH604: Error running JSON-RPC server: The Http server returned error status code: HTTP status server error (500 Internal Server Error) for url (https://api.avax-test.network/ext/bc/C/rpc)

### Minimal reproduction steps

My hardhat.config.js:
```
require("@nomicfoundation/hardhat-toolbox");

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  defaultNetwork: "hardhat",
  solidity: "0.8.24",
  networks: {
    hardhat: {
      forking: {
        url: "https://api.avax.network/ext/bc/C/rpc",
      },
    },
  }
};
```
Starting the node with the command:
`npx hardhat node`

### Search terms

avax avalanche hh604

**Comment by fvictorio** [comment]
My guess is that this was either a temporary error in the provider (hence the 500 code), or something that was fixed in our latest release. Tentatively closing.
