### ISSUE TITLE
Sort out the logic of `npx hardhat test` command

### ISSUE THREAD

**Issue by jwbda** [NomicFoundation/edr#363]
Hi, @Wodann @agostbiro 🙂️

After several days learning, I think edr is really good in `npx hardhat test` command.

And I'm trying to sort out the logic of `npx hardhat test` command. And met some question, I hope you guys would help if you have some time. Here is the things: 
- 1 . Run the command `npx hardhat test`  in `Javascript Debug Terminal`
- 2 . And code execution to [const provider = await Provider.withConfig(](https://github.com/NomicFoundation/hardhat/blob/a1a385c45c7d9b92b38ca599b0d096197833feff/packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts#L239) of `packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts` file

And here is the question: 
1. How the code  [const provider = await Provider.withConfig(](https://github.com/NomicFoundation/hardhat/blob/a1a385c45c7d9b92b38ca599b0d096197833feff/packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts#L239)  of `packages/hardhat-core/src/internal/hardhat-network/provider/provider.ts` file run to code [static withConfig(context: EdrContext, config: ProviderConfig, loggerConfig: LoggerConfig, subscriberCallback: (event: SubscriptionEvent) => void): Promise<Provider>](https://github.com/NomicFoundation/hardhat/blob/a1a385c45c7d9b92b38ca599b0d096197833feff/crates/edr_napi/index.d.ts#L389) of `crates/edr_napi/index.d.ts` file ?
2. Where is the implementation of  `withConfig` method?
3. How does the file `index.js` and `index.d.ts` of `crates/edr_napi` generated? How can I reproduce them again if I delete them?
4. Last, How to let the breakpoint of  `Javascript Debug Terminal` of vscode come into `crates/edr_napi` to follow the logic of rust code?

And any reply would be appreciated, thanks in advance.

**Comment by fvictorio** [comment]
Hi @jwbda, I think you will find the answers to most of your questions by reading the [NAPI-RS](https://napi.rs/docs/introduction/getting-started) docs. The short answer is that anything imported in js from `@nomicfoundation/edr` will have a Rust equivalent under the `edr_napi` package (albeit with `snake_case` instead of `camelCase`).

> Last, How to let the breakpoint of Javascript Debug Terminal of vscode come into crates/edr_napi to follow the logic of rust code?

Sadly this is not possible as far as we know :disappointed:
