### ISSUE TITLE
Find repositories that use `anvil` for Hardhat tests

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#367]
**Definition of Done**
A list of repositories that run `anvil` in the background when running `hardhat test --network localhost`

**Comment by agostbiro** [comment]
Some results using Github search: https://github.com/search?q=%40foundry-rs%2Fhardhat-anvil&type=code

**Comment by fvictorio** [comment]
Won't do. This turned out to not be done a lot, which meant that we couldn't find useful examples.
