### ISSUE TITLE
Run benchmarks to compare `anvil` performance with `edr`

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#368]
**Depends on**
#367 

**Definition of Done**
Benchmark results showcasing how Hardhat with EDR performs when compared to Hardhat with Anvil

**Comment by fvictorio** [comment]
We have a very basic benchmark using a subset of OZ tests.

**Comment by Wodann** [comment]
Do you have steps for reproducing this, @fvictorio ?

**Comment by fvictorio** [comment]
https://nomicfoundation.notion.site/Public-Running-OZ-in-anvil-and-hh-node-0a49b60427164fa5b958dff18b0b63b8
