### ISSUE TITLE
Can we query optimism-specific transactions?

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#376]
**Definition of Done**
- The ability to have in-memory representations of Optimism-specific transaction types
- Answer the question: Can we have optimism and non-optimism transactions side-by-side in a single provider class?

**Comment by Wodann** [comment]
See https://github.com/NomicFoundation/edr/issues/377#issuecomment-2098784211 for how we can work around the `optimism` feature flag limitation.

With this in place, we should:
- be able to have in-memory representations of Optimism-specific transaction types based on [this code](https://github.com/paradigmxyz/reth/blob/main/crates/primitives/src/transaction/optimism.rs#L12)
- be able to have optimism and non-optimism transactions side-by-side in a single provider class using generics and a `trait ChainSpec` which specifies types

**Comment by fvictorio** [comment]
> There is an optimism handle register with custom bytecodes

Can you expand on this?

**Comment by Wodann** [comment]
> > There is an optimism handle register with custom bytecodes
> 
> Can you expand on this?

I fixed the wording. They're not custom bytecode. Rather, custom handler logic which is used in the EVM
