### ISSUE TITLE
Stop using batch calls

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/edr#381]
We use batch calls during forking for a couple of things (genesis accounts initialization, metadata, receipts). The problem is that Alchemy sometimes return 429 errors in the individual responses of the batch call, instead of bubbling it up to the HTTP response. This means that these requests are not retried.

The simplest solution seems to be to just avoid using batch calls. We can manually evaluate the performance impact, but we suspect it's not going to be a big deal.

**Comment by kowalski** [comment]
@fvictorio I've see your PR got merged :pray:

Could you please let me know when y'all plan the next public release? Perhaps there is a alpha build somewhere I could use to try on my end?

**Comment by fvictorio** [comment]
Hey @kowalski, we'll release this early next week, hopefully on Monday!

**Comment by fvictorio** [comment]
@kowalski version 0.3.7 of `@nomicfoundation/edr` should have fixed this.

You can get this version by removing your lockfile and re-installing the packages; this will use the latest EDR version when installing Hardhat. Alternatively, you can wait until the next version of Hardhat, which [will have this bumped dependency](https://github.com/NomicFoundation/hardhat/pull/5173).

**Comment by kowalski** [comment]
@fvictorio I confirm it works well now! I really appreciate you expediting this :heart:
