### ISSUE TITLE
Replay block failure: 19645342

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/edr#383]
This block produces a different result. At least the receipts root is different (it might have other differences, but I could only spot that one on my phone).

Edit: 19652658 fails too, also with a receipts root difference.

**Comment by Wodann** [comment]
I confirmed locally that block number 19652658 works too after the fix.

**Comment by fvictorio** [comment]
Ah, sorry, I didn't realize that the PR wasn't merged yet. Thanks!
