### ISSUE TITLE
Large block timestamps cause issues

### ISSUE THREAD

**Issue by area** [NomicFoundation/edr#399]
### Version of Hardhat

2.22.3

### What happened?

Seemingly with the recent move to the EDR, block timestamps are limited to ones that fit inside a U64. This leads to valid (albeit pathological) behaviour causing hardhat to break:

```
ProviderError: data did not match any variant of untagged enum U64OrUsize at line 1 column 110
```

Comparing the [solidity docs](https://docs.soliditylang.org/en/latest/units-and-global-variables.html#block-and-transaction-properties) to the [EDR types](https://github.com/NomicFoundation/edr/blob/a02fa13fd3f5caf57dfdeb77a4d0105107028696/crates/edr_eth/src/block.rs#L158-L181), I suspect the same is true for other properties, and though don't have demonstration here for other properties, it appears the behaviour required to trigger such issues would be more reasonable than what I'm showing here. The 'correct' reference point for these is presumably the Yellow Paper, but easier to find and link to the appropriate place in the Solidity Docs :sweat_smile: 

I will note that previous versions of hardhat - I believe prior to the move to the EDR - allowed this, and the timestamp was correctly set; an appropriate `curl` command for `eth_getBlockByNumber` would return the block data with the large timestamp. Trying to call `web3.eth.getBlock('latest')` in the hardhat console, however, would result in an error as the timestamp would try to be coerced to a number, and fail due to being too large.

### Minimal reproduction steps

```
npx hardhat console
helpers = require("@nomicfoundation/hardhat-network-helpers");
ethers = require('ethers')
helpers.time.increase(ethers.BigNumber.from(2).pow(256).sub(1).div(1000000000))
```
Results in 
```
ProviderError: data did not match any variant of untagged enum U64OrUsize at line 1 column 110
    at HttpProvider.request (/home/alex/colony/colonyNetwork/node_modules/hardhat/src/internal/core/providers/http.ts:90:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.increase (/home/alex/colony/colonyNetwork/node_modules/@nomicfoundation/hardhat-network-helpers/src/helpers/time/increase.ts:29:3)
```

### Search terms

timestamps, overflow

**Comment by area** [comment]
I stumbled across this while writing a test to demonstrate that all possible overflows were accommodated for in a contract. For what it's worth, I would not have been able to write this test 'natively' even with the older version (at least as I was trying to), due to the attempt to cast the timestamp to a number when fetching the block data - in [ethers](https://docs.ethers.org/v6/api/providers/#Block), the timestamp is a number, so I would have had to fall back making and parsing lower-level provider requests myself. That at least would have been possible with the older version, however.

**Comment by fvictorio** [comment]
Looking into this again, I'm starting to think that this is the desired behavior. Notice that the fact that `block.timestamp` in solidity is a `uint256` doesn't mean that actual block timestamps can be that big. In fact, [geth uses a u64 type for them](https://github.com/ethereum/go-ethereum/blob/86a1f0c39494c8f5caddf6bd9fbddd4bdfa944fd/core/types/block.go#L78).

I do think that the error message should be better, but that's a separate discussion.

Would it be too annoying for you to update your tests to use "smaller" increases? `2**64` is 584 billion years in the future, so it should be enough for most purposes :sweat_smile:

**Comment by fvictorio** [comment]
Yeah, I agree with your interpretation of the yellow paper. But I also think that it makes sense to keep this behavior for now (although I'm willing to be convinced otherwise).

I'm tentatively closing this, but happy to re-open if someone strongly feels that this should be changed.
