### ISSUE TITLE
Version `0.3.6` missing for `edr-darwin-x64`

### ISSUE THREAD

**Issue by bearpebble** [NomicFoundation/edr#414]
Looking at npm, all of the arch specific edr packages have received updates very recently.
The package [`edr-darwin-x64`](https://www.npmjs.com/package/@nomicfoundation/edr-darwin-x64?activeTab=versions) is somehow missing though and still stuck on version `0.3.5`, which was updated 13 days ago.

**Comment by fvictorio** [comment]
Thanks @bearpebble, this is a problem with our release pipeline. I'm looking into it, and we'll publish the proper version asap.

**Comment by fvictorio** [comment]
@bearpebble we just published 0.3.7, which should have the right builds for every OS/architecture combination we support.
