### ISSUE TITLE
Make release workflow more robust

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/edr#421]
When publishing 0.3.6, we had an issue where one of the builds wasn't published. The underlying reason was that the meaning of `macos-latest` as an OS value changed since the last release. This was fixed in https://github.com/NomicFoundation/edr/pull/415, but we should make some deeper changes to prevent this from happening again.

At the very least, we should add a step that checks that all the `crates/edr_napi/npm` directories have a `.node` file, or fail otherwise. But there might be other things we can do instead or in addition to this.

**Comment by Xanewok** [comment]
While we some some involved infrastructure in Slang, we also happen to do the check for that (and instrument the napi build a bit more ourselves) in https://github.com/NomicFoundation/slang/blob/3845dc78da4a29eccaa3193417ffd9506fab697d/crates/infra/cli/src/toolchains/napi/cli.rs#L88-L92.

Not saying we should do the same but maybe there is some helpful logic that we could carry over here.
