### ISSUE TITLE
Make CI run faster

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/edr#439]
The [EDR](https://github.com/NomicFoundation/edr/actions/workflows/edr-ci.yml) workflow takes more than 25 minutes to run. We should check if there's room for improvement here.

One easy gain is to remove the dependency between the tests and the "Check EDR" job. That would save some minutes, and the only downside is that we "waste" some computing time by running the tests when the build/lint fails.

We should also consider taking the slowest tests and only running them in main or during pre-release.

**Comment by Wodann** [comment]
There might be a simpler fix for this. We set the Cargo profile for tests to be optimised, but this means that builds take longer. We should see whether this tradeoff is worth it in CI/locally

**Comment by alcuadrado** [comment]
I think the cache and solc changes in this PR can be extra relevant here:  https://github.com/NomicFoundation/hardhat/pull/5184/files
