### ISSUE TITLE
Integrate EDR with solidity-coverage

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#44]
**Definition of Done**
Ensure that Hardhat with EDR works in `solidity-coverage`

**Comment by Wodann** [comment]
Solidity coverage hooks into the exposed `ethereumjs` vm and adds a callback handler to the `"step"` event (see [code](https://github.com/sc-forks/solidity-coverage/blob/master/lib/api.js#L299))

With Rethnet, we are currently only outputting complete traces at the end of a transaction. This should however be sufficient for the use case of `solidity-coverage`.

**Comment by fvictorio** [comment]
Yes, I believe they don't have to happen in "real time". If we just traverse the trace at the end and call a proper callback, then `solidity-coverage` should continue to work.

**Comment by agostbiro** [comment]
Do we have tests for `solidity-coverage` integration?

**Comment by Wodann** [comment]
https://github.com/sc-forks/solidity-coverage/pull/817

**Comment by agostbiro** [comment]
Done in https://github.com/NomicFoundation/hardhat/pull/4461
