### ISSUE TITLE
No known hardfork for execution on historical block

### ISSUE THREAD

**Issue by MarcBickel** [NomicFoundation/edr#447]
### Version of Hardhat

2.22.3

### What happened?

Forked arbitrum sepolia with `npx hardhat node`, when trying to run a typescript script that calls any function on-chain (even simple view function), I get the error 
`ProviderError: No known hardfork for execution on historical block 42324641 (relative to fork block number 42324641). The node was not configured with a hardfork activation history.`

The block number is the block at which the chain has been forked I believe (didn't specify so should be `latest`).

### Minimal reproduction steps

Fork arbitrum sepolia with `npx hardhat node` with an alchemy endpoint.

**Comment by fvictorio** [comment]
Hi, I can't reproduce this. I'm forking sepolia and running a call with some random ERC-20:

```js
const blockNumber = await ethers.provider.getBlockNumber()
const mockDai = await ethers.getContractAt(["function totalSupply() public view returns(uint256)"], "0xd6a17186e7bde277ad70e5d5c99d042acf30990c")
console.log(await mockDai.totalSupply())
console.log(await mockDai.totalSupply({blockTag: blockNumber - 10}))
```

Could someone give us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by MarcBickel** [comment]
Steps to reproduce: 

1. Have a hardhat config file
```
defaultNetwork: "arbitrumSepolia",
  solidity: {
    version: "0.8.25",
    settings: {
      viaIR: true,
      optimizer: {
        enabled: true,
        runs: 10,
        details: {
          yulDetails: {
            optimizerSteps: "u",
          },
        },
      },
      evmVersion: "cancun",
    },
  }
networks: {
    hardhat: {
      forking: {
        enabled: true,
        url: `https://arb-sepolia.g.alchemy.com/v2/<APIKEY>`,
      },
    }
```

2. Run `npx hardhat node --fork https://arb-sepolia.g.alchemy.com/v2/<APIKEY>` 
3. Run `npx hardhat run --network localhost scripts/testMultiContract.ts` (or any script). 
The first lines of the script are (after getting the accounts) as follows. Most likely hangs with any eth_call though. 
```
const currencyContract = "0xB28bbA1a16eB2aB0B0E4396f90BFbC04B6e344dC";
  const USDT = await ethers.getContractAt("TestnetERC20", currencyContract);
  const currencyDecimals = Number(await USDT.decimals());
```

4. Get an error

<img width="1479" alt="Screenshot 2024-05-15 at 12 19 28" src="https://github.com/NomicFoundation/edr/assets/13186695/7a13a5d7-36b1-4138-bebd-ec68ff9ed4ae">

```
ProviderError: No known hardfork for execution on historical block 44273914 (relative to fork block number 44273914). The node was not configured with a hardfork activation history.
    at HttpProvider.request (/Users/marc/Documents/Fume-Protocol/node_modules/hardhat/src/internal/core/providers/http.ts:90:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async staticCallResult (/Users/marc/Documents/Fume-Protocol/node_modules/ethers/src.ts/contract/contract.ts:337:22)
    at async staticCall (/Users/marc/Documents/Fume-Protocol/node_modules/ethers/src.ts/contract/contract.ts:303:24)
    at async Proxy.decimals (/Users/marc/Documents/Fume-Protocol/node_modules/ethers/src.ts/contract/contract.ts:351:41)
    at async main (/Users/marc/Documents/Fume-Protocol/scripts/testMultiContract.ts:19:39)
```

**Comment by MarcBickel** [comment]
@fvictorio Is that enough or do you need more info?

**Comment by fvictorio** [comment]
Confirmed and important, thanks!

**Comment by fvictorio** [comment]
I hope we can fix this soon, but in the meantime: a workaround seems to be to immediately mine a block after starting the node. For example, adding this at the beginning of the script:

```js
import * as helpers from "@nomicfoundation/hardhat-network-helpers";

await helpers.mine()
// rest of the script
```

**Comment by MarcBickel** [comment]
@fvictorio Thanks for the workaround, can confirm this does fix the problem, at least temporally 👍 
(I put the `await helpers.mine()` in `main()` if someone else also needs the workaround)

**Comment by SrikanthAlva** [comment]
> I hope we can fix this soon, but in the meantime: a workaround seems to be to immediately mine a block after starting the node. For example, adding this at the beginning of the script:
> 
> ```js
> import * as helpers from "@nomicfoundation/hardhat-network-helpers";
> 
> await helpers.mine()
> // rest of the script
> ```

I am using 2.22.5.

Didnt downgrade. 

used the code shared above. It resolved my issue.
