### ISSUE TITLE
Test Hardhat with EDR in community modules

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#45]
**Depends on**
- [x] #48 

**Definition of Done**
Test for the following community modules are passing using Hardhat with EDR:

- [ ] https://github.com/sc-forks/solidity-coverage
- [ ] https://github.com/cgewecke/hardhat-gas-reporter
- [x] https://github.com/defi-wonderland/smock/

**Comment by fvictorio** [comment]
Closing in favor of https://github.com/NomicFoundation/edr/issues/299, https://github.com/NomicFoundation/edr/issues/300 and https://github.com/NomicFoundation/edr/issues/301
