### ISSUE TITLE
eth_sign arguments are reversed

### ISSUE THREAD

**Issue by area** [NomicFoundation/edr#455]
### Version of Hardhat

2.22.4

### What happened?

Calling `eth_sign` via RPC against a node run with `npx hardhat node` does not work and returns an error.

### Minimal reproduction steps

```
npx hardhat node
curl -H 'Content-Type: application/json' http://127.0.0.1:8545 -X POST --data-raw '{"method":"eth_sign","params":["0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199","0x06fdde03"],"id":574,"jsonrpc":"2.0"}'
```
returns
```
{"jsonrpc":"2.0","id":574,"error":{"code":-32602,"message":"invalid value \"0x06fdde03\" supplied to : ADDRESS at line 1 column 89","data":{"message":"invalid value \"0x06fdde03\" supplied to : ADDRESS at line 1 column 89","data":{"method":"eth_sign","params":["0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199","0x06fdde03"]}}}}
```

Reversing the arguments:

```
curl -H 'Content-Type: application/json' http://127.0.0.1:8545 -X POST --data-raw '{"method":"eth_sign","params":["0x06fdde03", "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"],"id":574,"jsonrpc":"2.0"}'
```

and a signature is returned as expected

```
{"jsonrpc":"2.0","id":574,"result":"0x59002ebdb95ef3b258613f6bba6e91fd392bc49d86ad8a1e1afd32b929ee572968529c9189dde90d4a0d315132fcce215b28bfa479fe44cb05021a51e37ab6b81c"}
```

However, the [specification](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_sign) says that the address doing the signing should be the first argument, with the message to sign being second.

Like https://github.com/NomicFoundation/edr/issues/399, this was run across this upgrading from a pre-EDR hardhat to a post-EDR hardhat, so it's possible the issue is there, but haven't (successfully) investigated. The text of the error being returned is certainly from EDR, but where the mistake is in the stack is unclear.

### Search terms

eth_sign, RPC, EDR

**Comment by fvictorio** [comment]
Ugh, thanks a lot for reporting this @area. I didn't confirm this manually, but [this code](https://github.com/NomicFoundation/edr/blob/a62944fe01572eed4029d9fa3ed4d82e3c0af50d/crates/edr_provider/src/requests/methods.rs#L215-L216) is clearly wrong.

For reference, here are the previous implementations of [`eth_sign`](https://github.com/NomicFoundation/hardhat/blob/ethereumjs/main/packages/hardhat-core/src/internal/hardhat-network/provider/modules/eth.ts#L1074-L1081) and [`personal_sign`](https://github.com/NomicFoundation/hardhat/blob/2a280a7aa88aa2882e1512a8ce8febda6e7fe819/packages/hardhat-core/src/internal/hardhat-network/provider/modules/personal.ts#L32-L39): they do exactly the same thing but the params have a different order.
