### ISSUE TITLE
Integrate EDR with smock

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#46]
**Definition of Done**
Ensure that Hardhat with EDR works with `smock`

**Comment by Wodann** [comment]
smock [stores a reference to ethereumjs' vm](https://github.com/defi-wonderland/smock/blob/dev/src/sandbox.ts#L82) by accessing it through the Hardhat API. It uses this API to:
- [perform callback handling](https://github.com/defi-wonderland/smock/blob/dev/src/observable-vm.ts#L17) for the `"beforeMessage"` and `"afterMessage"` evm events
- [calling the vm's state manager API](https://github.com/defi-wonderland/smock/blob/dev/src/observable-vm.ts#L22) to [`putContractCode`, `getContractStorage`, and `putContractStorage`](https://github.com/defi-wonderland/smock/blob/dev/src/types.ts#L23)

With Rethnet, we are currently only outputting complete traces at the end of a transaction. This should however be sufficient for the use case of `smock`, as its already always piping all received before- and after-messages.

To allow community modules mutable access to the state, we could expose an interface inspired by ethereumjs-statemanager's `interface StateAccess`. This interface should ensure that modifications are not only applied to the state but the diff is also logged in the undo/redo stack.

**Comment by fvictorio** [comment]
> With Rethnet, we are currently only outputting complete traces at the end of a transaction. This should however be sufficient for the use case of `smock`, as its already always piping all received before- and after-messages.

Agree.



> To allow community modules mutable access to the state, we could expose an interface inspired by ethereumjs-statemanager's `interface StateAccess`. This interface should ensure that modifications are not only applied to the state but the diff is also logged in the undo/redo stack.

A simpler option might be to just ask them to go through the JSON-RPC layer for these things.

**Comment by agostbiro** [comment]
As I understand, this would require changes in `smock`?

**Comment by agostbiro** [comment]
Additional question: do we have tests for `smock` integration?

**Comment by fvictorio** [comment]
> As I understand, this would require changes in `smock`?

Not necessarily. We could have a fake object that simulates the same behavior we have now but that uses the new components under the hood.



> Additional question: do we have tests for `smock` integration?

Same answer as in https://github.com/NomicFoundation/edr/issues/44#issuecomment-1737321778
