### ISSUE TITLE
Research API for exposing EDR node to community modules

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#47]
As we're removing ethereumjs-vm, we'll need to expose our own API to Hardhat community modules. In particular, #44 #45 #46. This research should figure out the minimal API that we need in order to keep supporting these (and other) community modules.

**Comment by fvictorio** [comment]
From skimming the code of those projects, my understanding is that we mainly need some hooks for the step, beforeMessage and afterMessage event. Of course, if we do this we might as well add a complete set of hooks (before and after tx, and maybe others).

Smock also uses the state manager directly, but I believe that's not necessary and everything can be done through the JSON-RPC. I'm waiting for them to confirm this.

All of this is a preliminary guess. When the time comes we might find subtler problems, but I think this should get us 80% there (though you know what they say about the other 20%...)

**Comment by Wodann** [comment]
If possible, I'd like to avoid having callbacks from Rust to JS - to avoid the interop overhead. Would it be possible for them to operate on a call trace that's output at the end of the call as well?

The call trace would be call tree/hierarchy with all information at each step included.

**Comment by fvictorio** [comment]
I think that would be possible, but it would make transitioning those plugins harder.

I think we are going to have data soon about how much that interop impacts performance. If it's terrible, maybe it's better to not have callbacks like these, or to have them with a big warning about performance. But I'd say we decide after profiling this.

**Comment by alcuadrado** [comment]
> If possible, I'd like to avoid having callbacks from Rust to JS - to avoid the interop overhead. Would it be possible for them to operate on a call trace that's output at the end of the call as well?

I think we need to expose those, documenting the performance hit, and try for the default setup not to use them. But we need to provide the capabilities for consumers.

**Comment by Wodann** [comment]
For backwards compatibility, I'm happy to provide that as an option 😃

I think, in general, callbacks are one means of solving the problem, so we could investigate more performant alternatives where we only cross "the boundary" once.

**Comment by zemse** [comment]
> If possible, I'd like to avoid having callbacks from Rust to JS - to avoid the interop overhead. Would it be possible for them to operate on a call trace that's output at the end of the call as well?
> 
> The call trace would be call tree/hierarchy with all information at each step included.

To avoid performance hits, it's better to operate on call trace. Is it possible to implement a filter while call trace is being generated? e.g. https://github.com/NomicFoundation/hardhat/issues/1668 for plugins to filter information and steps instead of getting everything that blows up memory usage.

**Comment by Wodann** [comment]
We'll use the same approach for EDR v0.2.0 as we used for v0.1.0, using a proxy in TS
