### ISSUE TITLE
Add option to activate hardfork using UNIX timestamp

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#532]
In EDR, we currently support configuration of hardfork activations using block numbers only. More commonly, UNIX timestamp are used to determine when blocks need to start being mined with a new hardfork.

**Definition of Done**
- Add the ability to activate hardforks using a UNIX timestamp
- Hardfork activation configuration should be mutually exclusive: either by timestamp or by block number
- Update hardfork activations to use timestamps, where applicable.

**Comment by alcuadrado** [comment]
> Update hardfork activations to use timestamps, where applicable.

Every hardfork before the merge uses block numbers. Every hardfork after it uses timestamps. I don't remember what was the criteria for the merge itself.
