### ISSUE TITLE
Error running JSON-RPC server: Missing nonce

### ISSUE THREAD

**Issue by jeremyjams** [NomicFoundation/edr#536]
## Context
Hello, I'm not able to fork a remote network using `edr@0.4.1`. For comparison, it was running smoothly with `edr@0.3.5`.
```
networks: {
    hardhat: {
        [...]
        forking: {
            url: 'https://bellecour.iex.ec',
        },
        [...]
    },
},
```

## Error
```
          throw new HardhatError(
                ^
HardhatError: HH604: Error running JSON-RPC server: Missing nonce
```

## Details
`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1B000B1", true],"id":1}' https://bellecour.iex.ec/`
```
{
  "jsonrpc": "2.0",
  "result": {
    "author": "0xa3b079e4b54d2886ccd9cddc1335743bf1b2f0ad",
    [...]
    "timestamp": "0x664d5713",
    "transactions": [],
    "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
    "uncles": []
  },
  "id": 1
}
```
Nonce is indeed missing in blocks of this (PoA) network.

**Comment by Wodann** [comment]
I fixed the issue, but we decided not to include a test in our test suite as we can't rely on a reliable endpoint like Alchemy or Infura.

We'll ship the fix ASAP in our next release.
