### ISSUE TITLE
Implement release workflow

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#63]
When releasing EDR as an `npm` package, we need to:

1. change the version from `major.minor.patch-dev` to `major.minor.patch`
2. cross-compile binaries for all supported target triples (see)
3. auto-generate a JS wrapper that select the correct binary
4. publish packages to `npm`
5. bump the version to the next semver version and append the `dev` suffix

Slang has already implemented a CLI tool to achieve (most) of these, which we can likely reuse. The PR implementing this CLI can be found [here](https://github.com/NomicFoundation/slang/pull/565/files#top). The files of interest are in `crates/infra/cli`.

We want a similar CLI tool for EDR. EDR-specific commands can live as duplicate code within our repository, but it would be good to create or use a general-purpose crate wherever possible.

**Definiton of Done**
- Create a CLI that supports commands 1 through 5 (listed above)
- Share as much of the common code between EDR and Slang (and potentially external crates)

**Comment by agostbiro** [comment]
Done in https://github.com/NomicFoundation/hardhat/pull/4415
