### ISSUE TITLE
Add generic chain type

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#635]
**Definition of Done**
- Add a `struct GenericChainSpec` (ideally in a new crate `edr_generic`)
- Implement the traits outlined in [the book](https://github.com/NomicFoundation/edr/blob/feat/multichain/book/src/04_multichain/01_chain_spec.md) for `GenericChainSpec` such that it can be used from Hardhat
- Treat unknown transaction types as `PostEip155Legacy` as [in the `main` branch](https://github.com/NomicFoundation/edr/blob/main/crates/edr_rpc_eth/src/transaction.rs#L271)
- Allow remote blocks to have a missing nonce [as in `main`](https://github.com/NomicFoundation/edr/blob/main/crates/edr_evm/src/block/remote.rs#L161) (also see [PR](https://github.com/NomicFoundation/edr/pull/539/files) with change)
- Reintroduce [this test](https://github.com/NomicFoundation/edr/blob/main/crates/edr_evm/tests/optimism.rs) alongside the `GenericChainSpec` implementation and validate it works (this test cannot work for `L1ChainSpec` as it would throw an error when detecting unknown transaction types)
- Add test to validate that the generic chain type can parse this `eth_getBlockByNumber` response (taken from [this issue](https://github.com/NomicFoundation/edr/issues/536)):
  ```json
  {"jsonrpc":"2.0","result":{"author":"0xa3b079e4b54d2886ccd9cddc1335743bf1b2f0ad","difficulty":"0xfffffffffffffffffffffffffffffffe","extraData":"0x4e65746865726d696e64","gasLimit":"0x663be0","gasUsed":"0x0","hash":"0x12a6d4673bc9a55b5f77d897f32eb0ff15bca32d09d3dff8013e3ff684b0a84d","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0xa3b079e4b54d2886ccd9cddc1335743bf1b2f0ad","number":"0x1b000b1","parentHash":"0x26046ba285c7c87ff04783347a5b63cba77d884a11a50a632ea68ba2843b3064","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","signature":"0x012bb653a98ede38cd88f59fb09c67a8628012e3a4bdd6925a3dee547e0c4f470aa3118d03e4c81b715200aeb34b00f7c67a0a9cd687ff26c2dbc82964d4268a00","size":"0x238","stateRoot":"0x62cb23bc47439bc73eef6bf9fc0e54b1a40ebb3b0cbcfefd6b13cbc79a1095b6","step":343268919,"totalDifficulty":"0x1b000b0ffffffffffffffffffffffffe9dc2118","timestamp":"0x664d5713","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]},"id":1}
  ```
- Replace the registration of the `L1` chain type in Hardhat with the `Generic` chain type.
- Validate that all Hardhat tests pass
- (optional) Incorporate the [feature for better error messages when running unknown transaction types](https://github.com/NomicFoundation/edr/commit/2f1c1896196082a9f62164fa45c0134f52565d89) by merging `main`
  - This was listed to keep track, but can be done in a follow-up PR

**Comment by Xanewok** [comment]
I'll close this as completed by #653 but feel free to re-open it if there's anything else to be done. I assume that the last, optional item on the list will be completed as we merge `main` into the feature branch in order to prepare it to land in `main` but I can also look into that if you'd like me to.
