### ISSUE TITLE
Use Alchemy URL from environment

### ISSUE THREAD

**Issue by agostbiro** [NomicFoundation/edr#643]
**Problem**

There still some hard-coded Alchemy credentials in the Solidity tests codebase (especially in .sol test files). This is a problem, because these publicly available keys are less reliable than per-user, potentially higher throughput keys. It's not high prio to fix it though as the RPC calls they're used for are heavily cached and we haven't seen any timeouts yet.

**Definition of Done**

When searching for `g.alchemy.com` or `alchemyapi.io`, there are no hard-coded credentials.

**Comment by KoxyG** [comment]
Kindly assign me to this @agostbiro

**Comment by agostbiro** [comment]
Hi @KoxyG thanks for volunteering to take care of this issue! I've assigned you now.  Please fork from the `feat/solidity-tests` branch and have your PR target this branch.

**Comment by agostbiro** [comment]
Btw, out of curiosity, how did you find this issue?

**Comment by KoxyG** [comment]
Thanks. I found it here. https://onchainsquad.com/oss/

**Comment by KoxyG** [comment]
I am done cloning from the "feat/solidity-tests" branch. What folder am i meant to work on?, is it the "hardhat-tests/test" folder?

**Comment by agostbiro** [comment]
@KoxyG the relevant files are int `crates/foundry` directory

**Comment by agostbiro** [comment]
Hi @KoxyG hope you're doing well. Wanted to check in if you need any help with this issue?

**Comment by KoxyG** [comment]
oh yes, for weeks i had issues cloning this repo. I just tried again and it worked.

I am on it now @agostbiro

**Comment by KoxyG** [comment]
Hi @agostbiro so i have a little issue here. On navigating to the "feat/solidity-tests" branch, I forked the project. On forking it from that branch, the "crates/foundry" directory is not available.

**Comment by agostbiro** [comment]
@KoxyG right, Github is not very intuitive on this. When you fork a repo, it'll only include the `main` branch in your fork no matter which branch you select in the UI when you fork. You can fix this with the following commands in your local copy of your fork:

```bash
# Add the original repo as the upstream target so you can pull the `feat/solidity-tests` branch
git remote add upstream https://github.com/NomicFoundation/edr.git
# Get the changes from the original repo
git fetch upstream
# Check out the `feat/solidity-tests` branch locally
git switch -c feat/solidity-tests upstream/feat/solidity-tests
# Now you have the `crates/foundry` directory
ls crates/foundry
```

**Comment by agostbiro** [comment]
Btw files have been moved around a bit since creating the issue, in addition to the `crates/foundry` directory, please also check the `crates/edr_solidity_tests/` directory in the `feat/solidity-tests` branch

**Comment by iosh** [comment]
@agostbiro You can assign this issue to me. My understanding is that fixing this issue involves replacing all hard-coded URLs with environment variables?

**Comment by agostbiro** [comment]
Yep that's correct @iosh . Thanks for taking over! @KoxyG hope you don't mind that I reassign to @iosh as I haven't heard from you in a while.

There is a helper function to get the env url here: https://github.com/NomicFoundation/edr/blob/37008232f781116b4a8fd80d70fa63031284b70f/crates/edr_test_utils/src/env.rs#L20

**Comment by iosh** [comment]
@agostbiro How should i change the URL in the `.sol` file? I think it might be use  the `rpcUrls` or `rpcUrl` function in `.sol` file ， but where should i set it the env? or is there another way to do this?

**Comment by agostbiro** [comment]
Done in https://github.com/NomicFoundation/edr/pull/707. Thanks, @iosh !
