### ISSUE TITLE
Implement `debug_traceTransaction` for EDR

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#65]
**Depends On**
- [x] #180

**Blocks**
- [ ] #101 

**Definition of Done**
- Implement the API proposed in #180
- Integrate API in Hardhat and support it for the Rethnet implementation of the evm

**Comment by Wodann** [comment]
Some additional refactoring is intended to happen in the future by @agostbiro. Could you please create an issue outlining all of the things that you'd like to include in the refactor?

**Comment by agostbiro** [comment]
> Some additional refactoring is intended to happen in the future by @agostbiro. Could you please create an issue outlining all of the things that you'd like to include in the refactor?

Thanks for the reminder, added here: https://github.com/NomicFoundation/edr/issues/197
