### ISSUE TITLE
Load RPC endpoints from `forge-std` config for benchmarks

### ISSUE THREAD

**Issue by agostbiro** [NomicFoundation/edr#709]
**Problem**

The Solidity test benchmark script hard codes the RPC endpoints for `forge-std`: 

https://github.com/NomicFoundation/edr/blob/37008232f781116b4a8fd80d70fa63031284b70f/crates/tools/js/benchmark/src/solidity-tests.ts#L172-L178

**Definition of Done**

Load the RPC endpoints from the `foundry.toml` in the `forge-std` repo which is checked out by the script locally:

https://github.com/NomicFoundation/forge-std/blob/6e05729b76f1ae0d437e74951aef1ca987788ab3/foundry.toml#L4-L8

**Comment by abdegenius** [comment]
Good morning @agostbiro can I jump on this, please assign me this issue...thank you

**Comment by abdegenius** [comment]
Hello @agostbiro am still available to handle this issue!

**Comment by agostbiro** [comment]
Hey, thanks and feel to submit a PR. It's a small change so I won't assign anybody

**Comment by agostbiro** [comment]
Done in https://github.com/NomicFoundation/edr/pull/715
