### ISSUE TITLE
Remove `enum` types from N-API

### ISSUE THREAD

**Issue by Wodann** [NomicFoundation/edr#721]
Hardhat is using [isolatedModules](https://www.typescriptlang.org/tsconfig/#isolatedModules) to ensure compatibility with single-file transpilation tools like tsx. With isolatedModules, const enums can’t be inlined, since this setting assumes each file compiles independently rather than together.

Instead of using enums, it would be better to generate constants, similar to what was done for [SpecId](https://github.com/NomicFoundation/edr/blob/feat/multichain/crates/edr_napi/src/chains/l1.rs#L126).

[original discussion](https://github.com/NomicFoundation/hardhat/pull/5840#issuecomment-2437953620)

**Definition of done**
Remove all instances of const enum types from the N-API in the [`feat/multichain` branch](https://github.com/NomicFoundation/edr/tree/feat/multichain)

**Comment by iosh** [comment]
@Wodann  @agostbiro Can i try this? and can you provide more detail information？ I didn't see any difference between `MineOrdering` and `SpecId` they're both `const enum`.

**Comment by agostbiro** [comment]
Thanks for your interest @iosh , I think the issue is in the `feat/multichain`, but I'm not up-to-date on the progress there, so I'll defer to @Wodann.

**Comment by Wodann** [comment]
Thank you for your interest, @iosh! I've added some links to point you in the right direction, but there two more requirements that I'm clarifying with the requester. Once that's done, I'll update the issue description and assign it to you 🙂

**Comment by alcuadrado** [comment]
I think another option is generating non-const enums. `const enum`s are so surprising/confusing.

**Comment by Wodann** [comment]
After discussing this, we realised that the solution was trivial and I implemented it in the above PR.

Thank you for your interest, @iosh! Please have a look at some of our other issues for a good first issue 😊
